### ISSUE TITLE
Synchronization on null

### ISSUE THREAD

**Issue by Leative** [mhisoft/common-utils#2]
One of the test cases causes an exception:
    
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in
    org.mhisoft.common.util.JceEnryptionTest
    org.mhisoft.common.util.JceEnryptionTest  Time elapsed: 0.001 s  <<< ERROR!
    java.lang.NullPointerException
        at org.mhisoft.common.util.JceEnryptionTest.setup(JceEnryptionTest.java:40)

In JceEncryption on line 69 you are synchronizing on null. Actually, both if statements (68, 70) are not useful there since the synchronization will always throw an exception in that case.

**Comment by x8699876** [comment]
fixed.
